image: Ubuntu1804  # образ для сборки
stack: Node.js v20.14.0.  # окружение
branches:
  only:
    - master  # ветка git
cache: node_modules  # кеширование
install:
  - npm install  # команда установки зависимостей
build: off  # отключаем встроенную в appveyor систему сборки
test_script:
  - npm run lint && npm test  # скрипт тестирования